"""
Core skill catalog — 64 SDLC skills as SkillMetadata instances.

Migrated from scripts/skills/skill_catalog.py.  This module is the
single source of truth for skill definitions inside the core package.
The scripts/ copy remains as a CLI wrapper only.

Usage::

    from core.skills.catalog import (
        SKILL_CATALOG,
        get_skill,
        get_skills_for_phase,
        get_skills_for_profile,
        get_skills_by_category,
        get_catalog_stats,
    )
"""

import logging
from collections import Counter
from typing import Any, Dict, List, Optional, Tuple

from core.skills.models import (
    PROFILE_SKILL_RULES,
    RiskLevel,
    SkillMetadata,
    risk_at_most,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Catalog data — 64 skills
# ---------------------------------------------------------------------------

SKILL_CATALOG: List[SkillMetadata] = [
    # ==================================================================
    # TACTICAL BUILTINS (20 skills)
    # ==================================================================

    # -- Formatting (3) --
    SkillMetadata(
        id="format-code",
        name="Format Code",
        description="Auto-format source code using language-appropriate formatters (black, prettier, gofmt, rustfmt). Runs the formatter and reports results without explanation.",
        sdlc_phases=[5, 6],
        category="formatting",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="lint-check",
        name="Lint Check",
        description="Run language-specific linters (ruff, eslint, golangci-lint) and report findings. No explanation or fix suggestions, just raw lint output.",
        sdlc_phases=[5, 6, 7],
        category="formatting",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="type-check",
        name="Type Check",
        description="Run static type checkers (mypy, tsc, pyright) and report type errors. Returns pass/fail with error locations.",
        sdlc_phases=[5, 6, 7],
        category="formatting",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),

    # -- Validation (4) --
    SkillMetadata(
        id="validate-json",
        name="Validate JSON",
        description="Parse and validate JSON files. Reports syntax errors with line numbers and character positions.",
        sdlc_phases=[0, 1, 2, 3, 4],
        category="validation",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="validate-yaml",
        name="Validate YAML",
        description="Parse and validate YAML files. Reports syntax errors and structural issues.",
        sdlc_phases=[0, 1, 4, 8],
        category="validation",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="validate-openapi",
        name="Validate OpenAPI",
        description="Validate OpenAPI/Swagger specification files for schema compliance and completeness.",
        sdlc_phases=[4, 5, 7],
        category="validation",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="validate-prd",
        name="Validate PRD",
        description="Quick completeness check on PRD documents. Verifies required sections, acceptance criteria, and traceability links exist.",
        sdlc_phases=[2, 3],
        category="validation",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),

    # -- Extraction (3) --
    SkillMetadata(
        id="extract-todos",
        name="Extract TODOs",
        description="Find TODO, FIXME, HACK, and NOTE comments across the codebase. Returns file paths, line numbers, and comment text.",
        sdlc_phases=[1, 5, 6],
        category="extraction",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="extract-functions",
        name="Extract Functions",
        description="List function and method signatures from source files. Returns name, parameters, return type, and file location.",
        sdlc_phases=[1, 4, 5],
        category="extraction",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="extract-imports",
        name="Extract Imports",
        description="List all import/require/include statements and map dependency usage across the codebase.",
        sdlc_phases=[1, 5, 6],
        category="extraction",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),

    # -- Git Operations (2) --
    SkillMetadata(
        id="quick-status",
        name="Quick Status",
        description="Git status summary: current branch, staged/unstaged changes, recent commits, and remote tracking state.",
        sdlc_phases=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        category="git-ops",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="quick-diff",
        name="Quick Diff",
        description="Git diff summary with file-level change statistics. Supports comparing against any ref (HEAD~N, branch, tag).",
        sdlc_phases=[5, 6, 7, 9],
        category="git-ops",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),

    # -- File Operations (3) --
    SkillMetadata(
        id="count-lines",
        name="Count Lines",
        description="Count lines of code by language using tokei/cloc. Reports per-language and total counts excluding blanks and comments.",
        sdlc_phases=[1, 5, 7],
        category="file-ops",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="find-duplicates",
        name="Find Duplicates",
        description="Detect duplicate or near-duplicate code blocks across the codebase. Reports file pairs with similarity scores.",
        sdlc_phases=[5, 6],
        category="file-ops",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="check-imports-unused",
        name="Check Unused Imports",
        description="Find unused import statements that can be safely removed. Supports Python, JavaScript, and TypeScript.",
        sdlc_phases=[5, 6],
        category="file-ops",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),

    # -- Phase Checks (3) --
    SkillMetadata(
        id="check-phase-outputs",
        name="Check Phase Outputs",
        description="Verify that required output artifacts exist for a given phase. Checks file presence, non-empty content, and expected structure.",
        sdlc_phases=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        category="phase-checks",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="check-test-coverage",
        name="Check Test Coverage",
        description="Run test coverage analysis and report percentage by module. Highlights uncovered files and low-coverage areas.",
        sdlc_phases=[5, 6, 7],
        category="phase-checks",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="phase-summary",
        name="Phase Summary",
        description="Display current pipeline phase progress: completed tasks, pending tasks, blockers, and time estimates.",
        sdlc_phases=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        category="phase-checks",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),

    # -- Doc Generation (2) --
    SkillMetadata(
        id="generate-changelog",
        name="Generate Changelog",
        description="Auto-generate changelog entries from git commit history. Groups by type (feat, fix, refactor) with links to commits.",
        sdlc_phases=[8, 9],
        category="doc-gen",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="generate-api-summary",
        name="Generate API Summary",
        description="Generate a concise API endpoint summary from OpenAPI specs or source code route definitions.",
        sdlc_phases=[4, 5, 8],
        category="doc-gen",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),

    # ==================================================================
    # COMMUNITY SKILLS -- superpowers (6 skills)
    # ==================================================================
    SkillMetadata(
        id="planning",
        name="Planning",
        description="Structured planning workflow: break down goals into milestones, define dependencies, estimate effort, and produce actionable plans.",
        sdlc_phases=[0, 1, 2, 3],
        category="architecture",
        source="community",
        source_url="https://github.com/obra/superpowers",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="research",
        name="Research",
        description="Systematic research workflow: gather information from codebase, docs, and context to answer architectural and technical questions.",
        sdlc_phases=[1, 2, 4],
        category="architecture",
        source="community",
        source_url="https://github.com/obra/superpowers",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="tdd",
        name="Test-Driven Development",
        description="RED-GREEN-REFACTOR workflow: write failing test first, implement minimal code to pass, then refactor. Enforces strict TDD discipline.",
        sdlc_phases=[5, 6, 7],
        category="testing",
        source="community",
        source_url="https://github.com/obra/superpowers",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="debugging",
        name="Systematic Debugging",
        description="Structured debugging workflow: reproduce, isolate, hypothesize, verify, fix. Maintains a hypothesis log throughout the session.",
        sdlc_phases=[5, 6, 7],
        category="testing",
        source="community",
        source_url="https://github.com/obra/superpowers",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="code-review-assistant",
        name="Code Review Assistant",
        description="Structured code review: check style, correctness, security, performance, and maintainability. Produces review comments with severity levels.",
        sdlc_phases=[6],
        category="testing",
        source="community",
        source_url="https://github.com/obra/superpowers",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="performance-optimization",
        name="Performance Optimization",
        description="Profile and optimize code: identify bottlenecks, suggest algorithmic improvements, benchmark before/after. Focuses on measurable gains.",
        sdlc_phases=[5, 6, 7],
        category="performance",
        source="community",
        source_url="https://github.com/obra/superpowers",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),

    # ==================================================================
    # COMMUNITY SKILLS -- trailofbits (6 skills)
    # ==================================================================
    SkillMetadata(
        id="security-audit",
        name="Security Audit",
        description="Comprehensive security audit using Trail of Bits methodology: threat modeling, attack surface analysis, vulnerability identification with CVSS scoring.",
        sdlc_phases=[1, 6, 7, 8],
        category="security",
        source="community",
        source_url="https://github.com/trailofbits/skills",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Read-only analysis, no code modification",
        well_known=True,
        official=False,
        license="Apache-2.0",
    ),
    SkillMetadata(
        id="dependency-scan",
        name="Dependency Scan",
        description="Scan project dependencies for known vulnerabilities using CVE databases. Reports severity, affected versions, and remediation paths.",
        sdlc_phases=[1, 5, 7, 8],
        category="security",
        source="community",
        source_url="https://github.com/trailofbits/skills",
        requires_internet=True,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Fetches CVE data from public databases",
        well_known=True,
        official=False,
        license="Apache-2.0",
    ),
    SkillMetadata(
        id="secrets-detection",
        name="Secrets Detection",
        description="Scan codebase for leaked secrets: API keys, tokens, passwords, private keys. Uses pattern matching and entropy analysis.",
        sdlc_phases=[5, 6, 7, 8],
        category="security",
        source="community",
        source_url="https://github.com/trailofbits/skills",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Read-only scanning, reports findings to stdout",
        well_known=True,
        official=False,
        license="Apache-2.0",
    ),
    SkillMetadata(
        id="fuzzing-harness",
        name="Fuzzing Harness",
        description="Generate fuzzing harnesses for target functions using AFL++, libFuzzer, or atheris. Creates seed corpus and runs initial fuzzing campaign.",
        sdlc_phases=[5, 7],
        category="security",
        source="community",
        source_url="https://github.com/trailofbits/skills",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=True,
        risk_level=RiskLevel.MEDIUM,
        risk_notes="Generates and executes test harness code; review generated code before running",
        well_known=True,
        official=False,
        license="Apache-2.0",
    ),
    SkillMetadata(
        id="static-analysis",
        name="Static Analysis",
        description="Run Semgrep and CodeQL rules against the codebase. Produces SARIF reports with finding locations, severity, and remediation guidance.",
        sdlc_phases=[5, 6, 7],
        category="security",
        source="community",
        source_url="https://github.com/trailofbits/skills",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Read-only analysis using local rule sets",
        well_known=True,
        official=False,
        license="Apache-2.0",
    ),
    SkillMetadata(
        id="supply-chain-audit",
        name="Supply Chain Audit",
        description="Audit software supply chain: verify package provenance, check for typosquatting, validate lock file integrity, review transitive dependencies.",
        sdlc_phases=[1, 7, 8],
        category="security",
        source="community",
        source_url="https://github.com/trailofbits/skills",
        requires_internet=True,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Queries public package registries for provenance data",
        well_known=True,
        official=False,
        license="Apache-2.0",
    ),

    # ==================================================================
    # EXTERNAL SKILLS -- playbooks / awesome-claude-code (20 skills)
    # ==================================================================
    SkillMetadata(
        id="react-best-practices",
        name="React Best Practices",
        description="Enforce React best practices: component composition, hooks usage, state management patterns, memo/callback optimization, and accessibility attributes.",
        sdlc_phases=[4, 5, 6],
        category="architecture",
        source="playbooks",
        source_url="https://github.com/anthropics/claude-code-playbooks",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=True,
        license="MIT",
    ),
    SkillMetadata(
        id="nextjs-patterns",
        name="Next.js Patterns",
        description="Apply Next.js architectural patterns: App Router conventions, server components, data fetching strategies, middleware, and ISR/SSG configuration.",
        sdlc_phases=[4, 5, 6],
        category="architecture",
        source="playbooks",
        source_url="https://github.com/anthropics/claude-code-playbooks",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=True,
        license="MIT",
    ),
    SkillMetadata(
        id="api-design",
        name="API Design",
        description="Design RESTful and GraphQL APIs following best practices: resource naming, versioning, pagination, error responses, and HATEOAS links.",
        sdlc_phases=[2, 4, 5],
        category="api",
        source="playbooks",
        source_url="https://github.com/anthropics/claude-code-playbooks",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=True,
        license="MIT",
    ),
    SkillMetadata(
        id="database-optimization",
        name="Database Optimization",
        description="Optimize database queries and schema: index analysis, query plan review, N+1 detection, connection pooling configuration, and migration safety checks.",
        sdlc_phases=[4, 5, 6],
        category="data",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="May suggest schema changes; review before applying migrations",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="docker-best-practices",
        name="Docker Best Practices",
        description="Audit and improve Dockerfiles: multi-stage builds, layer caching, security hardening, image size reduction, and healthcheck configuration.",
        sdlc_phases=[5, 8],
        category="deployment",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Reviews Dockerfiles; does not build or push images",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="ci-cd-pipeline",
        name="CI/CD Pipeline",
        description="Generate and audit CI/CD configurations for GitHub Actions, GitLab CI, or CircleCI. Covers build, test, lint, security scan, and deploy stages.",
        sdlc_phases=[5, 7, 8],
        category="deployment",
        source="playbooks",
        source_url="https://github.com/anthropics/claude-code-playbooks",
        requires_internet=True,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=True,
        risk_level=RiskLevel.MEDIUM,
        risk_notes="Generates workflow files that run in CI; review before committing",
        well_known=True,
        official=True,
        license="MIT",
    ),
    SkillMetadata(
        id="terraform-infrastructure",
        name="Terraform Infrastructure",
        description="Generate and review Terraform configurations: resource definitions, state management, module composition, and plan review before apply.",
        sdlc_phases=[8],
        category="deployment",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=True,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=True,
        risk_level=RiskLevel.HIGH,
        risk_notes="Infrastructure as code affects cloud resources; always run plan before apply",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="kubernetes-deployment",
        name="Kubernetes Deployment",
        description="Generate and validate Kubernetes manifests: deployments, services, ingress, RBAC, resource limits, and readiness/liveness probes.",
        sdlc_phases=[8, 9],
        category="deployment",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=True,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=True,
        risk_level=RiskLevel.HIGH,
        risk_notes="Kubernetes manifests affect live clusters; validate in staging first",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="monitoring-setup",
        name="Monitoring Setup",
        description="Configure monitoring and alerting: Prometheus metrics, Grafana dashboards, alert rules, SLO definitions, and on-call escalation policies.",
        sdlc_phases=[8, 9],
        category="monitoring",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=True,
        requires_saas=True,
        saas_dependencies=["prometheus", "grafana"],
        security_scan_needed=False,
        risk_level=RiskLevel.MEDIUM,
        risk_notes="Connects to monitoring SaaS endpoints; credentials required",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="error-tracking",
        name="Error Tracking",
        description="Integrate error tracking services: Sentry SDK setup, source map upload, release tracking, alert configuration, and issue grouping rules.",
        sdlc_phases=[5, 8],
        category="monitoring",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=True,
        requires_saas=True,
        saas_dependencies=["sentry"],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Requires Sentry DSN; SDK sends error data to Sentry servers",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="accessibility-audit",
        name="Accessibility Audit",
        description="Audit web content for WCAG 2.1 compliance: color contrast, ARIA attributes, keyboard navigation, screen reader compatibility, and focus management.",
        sdlc_phases=[5, 6, 7],
        category="accessibility",
        source="playbooks",
        source_url="https://github.com/anthropics/claude-code-playbooks",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=True,
        license="MIT",
    ),
    SkillMetadata(
        id="seo-optimization",
        name="SEO Optimization",
        description="Audit and improve SEO: meta tags, structured data (JSON-LD), sitemap generation, canonical URLs, Core Web Vitals, and social graph tags.",
        sdlc_phases=[5, 6, 8],
        category="performance",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="graphql-schema",
        name="GraphQL Schema",
        description="Design and validate GraphQL schemas: type definitions, resolver patterns, N+1 prevention with DataLoader, pagination (cursor/offset), and schema stitching.",
        sdlc_phases=[4, 5],
        category="api",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="rest-api-testing",
        name="REST API Testing",
        description="Generate API test suites: endpoint coverage, authentication flows, error scenarios, rate limiting validation, and contract testing with OpenAPI specs.",
        sdlc_phases=[5, 7],
        category="testing",
        source="playbooks",
        source_url="https://github.com/anthropics/claude-code-playbooks",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=True,
        license="MIT",
    ),
    SkillMetadata(
        id="load-testing",
        name="Load Testing",
        description="Generate load test scripts for k6, Locust, or Artillery. Define scenarios, ramp-up profiles, and thresholds. Analyze results for bottlenecks.",
        sdlc_phases=[7, 8],
        category="performance",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=True,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.MEDIUM,
        risk_notes="Load tests generate significant traffic; run against staging, never production",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="mobile-responsive",
        name="Mobile Responsive",
        description="Audit and fix responsive design: breakpoint coverage, touch target sizes, viewport meta, fluid typography, and container query usage.",
        sdlc_phases=[5, 6],
        category="accessibility",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="internationalization",
        name="Internationalization",
        description="Audit and implement i18n: extract hardcoded strings, configure i18next/react-intl, handle plurals, RTL support, and locale-specific formatting.",
        sdlc_phases=[4, 5],
        category="architecture",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="authentication-patterns",
        name="Authentication Patterns",
        description="Implement authentication flows: JWT/session management, OAuth2/OIDC integration, MFA setup, CSRF protection, and secure cookie configuration.",
        sdlc_phases=[4, 5, 6],
        category="security",
        source="playbooks",
        source_url="https://github.com/anthropics/claude-code-playbooks",
        requires_internet=True,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=True,
        risk_level=RiskLevel.HIGH,
        risk_notes="Authentication code is security-critical; always review generated auth logic",
        well_known=True,
        official=True,
        license="MIT",
    ),
    SkillMetadata(
        id="caching-strategies",
        name="Caching Strategies",
        description="Design and implement caching layers: Redis/Memcached setup, cache invalidation patterns, CDN configuration, HTTP cache headers, and stale-while-revalidate.",
        sdlc_phases=[4, 5],
        category="performance",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Cache misconfiguration can serve stale data; test invalidation thoroughly",
        well_known=True,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="microservices-patterns",
        name="Microservices Patterns",
        description="Apply microservices patterns: service boundaries, API gateways, circuit breakers, saga orchestration, event sourcing, and distributed tracing.",
        sdlc_phases=[2, 4, 5],
        category="architecture",
        source="awesome-claude-code",
        source_url="https://github.com/wonhyeongseo/awesome-claude-code",
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Architectural guidance; review service boundary decisions carefully",
        well_known=True,
        official=False,
        license="MIT",
    ),

    # ==================================================================
    # CUSTOM / SYNTHESIZED SKILLS -- atomic-claude-specific (12 skills)
    # ==================================================================
    SkillMetadata(
        id="prd-authoring",
        name="PRD Authoring",
        description="Guide PRD creation: stakeholder identification, problem statement, user stories, acceptance criteria, technical constraints, and scope boundaries.",
        sdlc_phases=[2],
        category="doc-gen",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="spec-writing",
        name="Spec Writing",
        description="Generate technical specifications from PRD requirements: data models, API contracts, sequence diagrams, and component interfaces.",
        sdlc_phases=[3, 4],
        category="doc-gen",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="task-decomposition",
        name="Task Decomposition",
        description="Break down features into implementation tasks: estimate complexity, identify dependencies, assign phases, and create task graphs.",
        sdlc_phases=[3],
        category="architecture",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="agent-orchestration",
        name="Agent Orchestration",
        description="Select and configure agents for task execution: match agent expertise to task requirements, resolve conflicts, and manage agent context.",
        sdlc_phases=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        category="architecture",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="memory-management",
        name="Memory Management",
        description="Manage pipeline memory: checkpoint creation, context compaction, memory recall optimization, and dual-write to file/graph stores.",
        sdlc_phases=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        category="data",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="graph-query-builder",
        name="Graph Query Builder",
        description="Build and execute FalkorDB Cypher queries: node/edge creation, traversal patterns, fulltext search, and result aggregation for the knowledge graph.",
        sdlc_phases=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        category="data",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.LOW,
        risk_notes="Write queries modify graph state; use read-only queries for exploration",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="audit-runner",
        name="Audit Runner",
        description="Execute audit categories from the 43-category audit framework: select categories, run checks, collect evidence, and produce scored reports.",
        sdlc_phases=[6, 7, 8],
        category="phase-checks",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="release-checklist",
        name="Release Checklist",
        description="Generate and track release checklists: version bump, changelog, tag, artifact build, smoke tests, rollback plan, and stakeholder notification.",
        sdlc_phases=[8, 9],
        category="deployment",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="rollback-procedures",
        name="Rollback Procedures",
        description="Generate rollback playbooks: database migration reversal, deployment rollback steps, feature flag toggles, and communication templates.",
        sdlc_phases=[8, 9],
        category="deployment",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.MEDIUM,
        risk_notes="Rollback procedures affect production state; test in staging first",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="incident-response",
        name="Incident Response",
        description="Structured incident response: severity classification, runbook selection, communication templates, root cause analysis, and post-incident review.",
        sdlc_phases=[9],
        category="monitoring",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.MEDIUM,
        risk_notes="Incident response may trigger automated actions; review runbooks before activation",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="compliance-check",
        name="Compliance Check",
        description="Validate compliance against frameworks: SOC2 controls, GDPR data handling, HIPAA safeguards, PCI-DSS requirements, and license compatibility.",
        sdlc_phases=[6, 7, 8],
        category="security",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
    SkillMetadata(
        id="cost-estimation",
        name="Cost Estimation",
        description="Estimate infrastructure and API costs: compute sizing, LLM token budgets, storage projections, bandwidth estimates, and monthly/annual forecasts.",
        sdlc_phases=[2, 4, 8],
        category="architecture",
        source="tactical-builtin",
        source_url=None,
        requires_internet=False,
        requires_saas=False,
        saas_dependencies=[],
        security_scan_needed=False,
        risk_level=RiskLevel.NONE,
        risk_notes="",
        well_known=False,
        official=False,
        license="MIT",
    ),
]

# ---------------------------------------------------------------------------
# Index for O(1) lookup
# ---------------------------------------------------------------------------

_SKILL_INDEX: Dict[str, SkillMetadata] = {s.id: s for s in SKILL_CATALOG}

# Validate count at import time
assert len(_SKILL_INDEX) == 64, (
    f"Expected 64 unique skills in SKILL_CATALOG, got {len(_SKILL_INDEX)}"
)

logger.debug("Skill catalog loaded: %d skills", len(SKILL_CATALOG))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_skill(skill_id: str) -> Optional[SkillMetadata]:
    """
    Look up a single skill by its kebab-case id.

    Returns:
        SkillMetadata or None if not found.
    """
    return _SKILL_INDEX.get(skill_id)


def get_skills_for_phase(phase_num: int) -> List[SkillMetadata]:
    """
    Return all skills that apply to a given SDLC phase (0-9).

    Returns:
        List of SkillMetadata sorted by id.
    """
    return sorted(
        [s for s in SKILL_CATALOG if phase_num in s.sdlc_phases],
        key=lambda s: s.id,
    )


def get_skills_for_profile(
    profile_name: str,
) -> Tuple[List[SkillMetadata], List[SkillMetadata]]:
    """
    Split the catalog into allowed and blocked skills for a profile.

    Args:
        profile_name: One of air_gapped, enterprise_secure, cloud_full, development
                      (must match core/features/profiles.py names).

    Returns:
        (allowed, blocked) -- two lists of SkillMetadata sorted by id.

    Raises:
        ValueError: If profile_name is not recognized.
    """
    if profile_name not in PROFILE_SKILL_RULES:
        raise ValueError(
            f"Unknown profile: {profile_name}. "
            f"Available: {sorted(PROFILE_SKILL_RULES.keys())}"
        )

    allowed: List[SkillMetadata] = []
    blocked: List[SkillMetadata] = []

    for skill in SKILL_CATALOG:
        if profile_name in skill.installable_in_profiles():
            allowed.append(skill)
        else:
            blocked.append(skill)

    return (
        sorted(allowed, key=lambda s: s.id),
        sorted(blocked, key=lambda s: s.id),
    )


def get_skills_by_category(category: str) -> List[SkillMetadata]:
    """
    Return all skills in a given category.

    Returns:
        List of SkillMetadata sorted by id.
    """
    return sorted(
        [s for s in SKILL_CATALOG if s.category == category],
        key=lambda s: s.id,
    )


def get_catalog_stats() -> Dict[str, Any]:
    """
    Return summary statistics for the catalog.

    Returns:
        Dict with counts by category, source, risk level, phase, and
        internet/saas requirements.
    """
    by_category: Counter = Counter()
    by_source: Counter = Counter()
    by_risk: Counter = Counter()
    by_phase: Counter = Counter()
    internet_count = 0
    saas_count = 0

    for skill in SKILL_CATALOG:
        by_category[skill.category] += 1
        by_source[skill.source] += 1
        by_risk[skill.risk_level.value] += 1

        for phase in skill.sdlc_phases:
            by_phase[phase] += 1

        if skill.requires_internet:
            internet_count += 1
        if skill.requires_saas:
            saas_count += 1

    return {
        "total_skills": len(SKILL_CATALOG),
        "by_category": dict(sorted(by_category.items())),
        "by_source": dict(sorted(by_source.items())),
        "by_risk_level": dict(sorted(by_risk.items())),
        "by_phase": dict(sorted(by_phase.items())),
        "requires_internet": internet_count,
        "requires_saas": saas_count,
    }
